@PORT = 3000

@HOST = http://localhost:{{PORT}}

GET {{HOST}}/api/products

### Recupero con filtro de precios:
GET {{HOST}}/api/products/min/100/max/300

###
POST {{HOST}}/api/products
Content-Type: application/json

{
    "name": "Thermomix",
    "description": "Hace muchos tipos de comida",
    "price": 1050,
    "stock": 23,
    "department": "home",
    "available": true
}

###
PUT {{HOST}}/api/products/66533e2851bf33d1e95c56b9
Content-Type: application/json

{
    "price": 105,
    "stock": 8,
    "available": true
}

###
DELETE {{HOST}}/api/products/66533e2851bf33d1e95c56b9